# Generated by Django 3.0.3 on 2020-03-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafmudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='Default Name', max_length=25),
        ),
    ]
