# Generated by Django 3.0.3 on 2020-03-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tafmudapp', '0002_player_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
