# Generated by Django 3.0.3 on 2020-03-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tafmudapp', '0002_world'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='room_id',
        ),
    ]
