# Generated by Django 3.0.3 on 2020-03-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafmudapp', '0003_remove_world_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='world_description',
            field=models.CharField(default='This is a default description', max_length=500),
        ),
        migrations.AddField(
            model_name='world',
            name='world_name',
            field=models.CharField(default='This is a default title', max_length=50),
        ),
    ]
