# Generated by Django 3.0.3 on 2020-03-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafmudapp', '0004_auto_20200304_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='world_description',
        ),
        migrations.RemoveField(
            model_name='world',
            name='world_name',
        ),
        migrations.AddField(
            model_name='world',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='world_grid',
            field=models.IntegerField(default=None),
        ),
    ]
