# Generated by Django 3.0.3 on 2020-03-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafmudapp', '0005_auto_20200304_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='loc_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='loc_y',
            field=models.IntegerField(default=0),
        ),
    ]
